### ISSUE TITLE
Instructions on how to go between ATO types

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#246]
## Problem Statement: 
- The 1 Year is inclusive of all the ATO steps. 
- Also 
    -  additional sections of the SSP must be completed
    -  additional controls are assessed
    -  a more thorough penetration test is done which may reveal other vulnerabilities 
    -  all need to be resolved before the ATO is granted
## Background information: 
This could use more detail, as we've had the question of how to go from a 90-day to a 1-year/3-year come up several times recently.
## Actions to take:  
- [x] Understand the ATO types
- [ ] Figure out the roles and responsibilities
- [ ] Set up conversation with GSA IT Security
## Acceptance criteria: 
- [ ] Documentation about how to go between is written 
## Supporting Documentation:
[The Types of ATO page](https://pages.18f.gov/before-you-ship/ato/types/#gsa-lato)

**Comment by its-a-lisa** [comment]
Made pull request for this task https://github.com/18F/before-you-ship/pull/433

**Comment by its-a-lisa** [comment]
@afeld & @JJediny are you good w/ me closing this issue without meeting the stated acceptance criteria? The pull request has been merged & that I believe meets the original intent of the issue.

**Comment by afeld** [comment]
Yep, that works, thanks!
