### ISSUE TITLE
checklist of things for systems on cloud.gov

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#259]
from an email from noah:

* [x] [Availability] Does the app have sufficient quota and therefore capacity in cloud.gov, both to withstand initial testing (which creates very heavy usage and traffic due to automated tools) and initial public or agency usage?
* [ ] [Availability] Have you fully completed a continuous integration and deployment pipeline?
* [ ] [Availability] Do you have the appropriate level of alerting set up with New Relic to send alerts to the appropriate Slack channels? Are the thresholds in New Relic for creating an alert conservative enough? (ByS covers this, but worth underlining)
* [ ] [Availability / Integrity] Do you have near complete test coverage, or at least test coverage over critical app functionality?
* [ ] [Integrity] Is both the business and technical process for updating or modifying the data fully understood and implemented? Does this process have a structure for authorization and authentication for the users who are responsible for the data? If the process is not automated, how will you / the agency be ensuring the data uploaded at its appropriate frequency?
* [ ] [Integrity] Do you have automated or manual tests to validate the data is accurate and is not malformed?

**Comment by afeld** [comment]
More in the new [proposed sprint schedule](https://docs.google.com/document/d/1RbwvYEphevhi4DuTA4lb99vPzyeVhNiS7-KlKTGYiwQ/edit).

**Comment by afeld** [comment]
> Have you fully completed a continuous integration and deployment pipeline?

While we should strongly encourage that projects do this, is it strictly required (or does it make a big difference) from an ATO perspective?

**Comment by afeld** [comment]
> Do you have automated or manual tests to validate the data is accurate and is not malformed?

I haven't heard of 18F projects doing this... While I like the idea, just want to confirm that this is a new req

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
