### ISSUE TITLE
ATO training

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#412]
## User Story:
As someone involved in the ATO process, I would like some training on what should be done. 
## Problem Statement: 
For instance the demand that the SSP not change after assessment starts is guidance, and not written anywhere.
## Background information: 
The easiest way to get system owners to the info they need without overwhelming them, and also to get some "guidance" written down, so there can be some actual discussion around it and whether it makes sense. 
## Actions to take:  
- [ ] Look into what training exists with GSA IT
- [ ] Look into creating training
- [ ] Look into buying training
## Acceptance criteria: 
- [ ] There is ATO training for TTS folks
## Supporting Documentation:
Direct quote [from Slack](https://gsa-tts.slack.com/archives/C2UUQ5CNP/p1569941192021700?thread_ts=1569934824.021400&cid=C2UUQ5CNP).
## Related Issues: 
https://github.com/18F/before-you-ship/issues/420 https://github.com/18F/tts-tech-portfolio/issues/236

**Comment by afeld** [comment]
Not a priority—closing.
