### ISSUE TITLE
Incorporate the ATO Process 18F presentation

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#420]
## User Story:
As someone explaining the ATO process, it would be good to have a presentation. 
## Background information: 
18F created presentation for the FEC and it is a great start that should be leveraged. 
## Actions to take:  
- [x] Modify slide deck with appropriate information
## Acceptance criteria: 
- [x] All the necessary changes have been made. 
## Supporting Documentation:
https://docs.google.com/presentation/d/1x-Bt8uyW-szHarglY57fFcC6PRCpUGFLe07uOvt93uk/edit
## Related Issues: 
https://github.com/18F/before-you-ship/issues/412

**Comment by LindsayYoung** [comment]
@LindsayYoung will update: last time I gave this, there were a few FEC details that confused some people. I think some of those details could be reframed in a way that makes it a bit more accessible to more situations.

**Comment by its-a-lisa** [comment]
Updated [slide deck](https://docs.google.com/presentation/d/1IJurX7Jc5XAQqmJSZtGZeJ8pk3IMfEIMRh1frmCpHlA/edit#slide=id.g760d0073da_0_345) with the following changes:

- Removed SEC specific information
- Put it in TTS template
- Added a role for 'Assessor'
- Modified the ATO components slide; changed "Documentation" to "Design" and added in the RMF steps 
- Changed the Steps for an ATO to two columns and added in system categorization 
    - This is something that can get expanded and we can add additional slides for different types of ATOs (custom software, COTs applications, SaaS, etc)
- Added a slide for the 3 necessary documents to obtain an authorization decision
- Modified the SSP, SAR and POA&M slides (took info from the DoD [tool](https://www.dau.edu/tools/t/Cybersecurity-and-Acquisition-Lifecycle-Integration-Tool-(CALIT)))
- Removed following slides (1) GSA ATOs (2) ATOs at other agencies (3) Other ATO options (4) System Diagram (5) Assessment example (6) Signing the ATO
     -- plan on putting those back in -- but waiting to see what happens w/ BYS for (1) and want to develop (2) , (3), (5) a little more and that be a slide deck on its own

Next steps: 
- [ ] Close this issue and open a new one to do the following
   - [ ] Tell @LindsayYoung how awesome original brief was & thanks for starting it off
   - [ ] Shared in the #g-security-compliance slack channel
   - [ ] Present at the security-compliance guild to get feedback
   - [ ] Start creating complementary slide deck w/ examples & stories

**Comment by afeld** [comment]
This issue was more about linking to the slides from Before You Ship 😉
