### ISSUE TITLE
move content to other sites

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#421]
Doesn't make sense to have it separate anymore.

User story: As a member of TTS staff, I don't want to have to look multiple places to learn about software/infrastructure/ATOs at TTS.

#### Acceptance Criteria
- [x] Solicit feedback on the idea/concept of merging this content into the handbook on slack.
- [x] Make a PR for the content to be merged into the TTS Handbook
- [x] Put in redirects

#### Linked Issues
Splitting up the work into separate issues for better tracking purposes.
* ~#525~
* ~#526~ 
* ~#527~
* ~#528~ 
* ~#529~ 
* ~#532~

**Comment by its-a-lisa** [comment]
Moved the ATO page to: https://github.com/18F/handbook/pull/1688 
Moved the Infrastructure page to: https://github.com/18F/handbook/pull/1688

Need to find a place for the following sections: 
Laws
508 - Accessibility
Paperwork Reduction Act (PRA)
Privacy

**Comment by tbaxter-18f** [comment]
I'd like to offer a counter-opinion:

The handbook doesn't really strive to be the definitive source of much of anything, certainly nothing so complex as ATOs and the many, many other issues one needs to be aware of when shipping software in a government context. It is, instead, a handbook. A guide book. A collection of pointers on a broad range of topics, that frequently points to other resources if one needs to dive in deeper into a given topic, whether that's ATOs, an HR topic, or whatever.

BYS, on the other hand, does aim to be authoritative and comprehensive. And generally speaking, it's pretty good at it.

I think the current state is ideal. We introduce people to concepts early and give them adequate information to get started, then direct them to the handbook for the full story and final word.

**Comment by its-a-lisa** [comment]
@afeld I referenced which pages I merged in the comment above

https://github.com/18F/before-you-ship/issues/421#issuecomment-559908877

**Comment by its-a-lisa** [comment]
Had a meeting today to discuss the topic; decided to close this issue out based on the following conversation:
- Look where there might be overlaps between Handbook & BYS
- Decided that having both is best based on the level of shallowness vs deep content
- Brought up that might need to mention some of the content in the Handbook so it comes up in the search index and can be redirected to the BYS
- Determine if there is content in BYS that is more suitable for the Handbook (Accessibility, Privacy, etc)
- Discussed that the Handbook is an all around resource and that BYS is specific to information that is relative to all
- Mentioned the feasibility of pulling the Development Guide into the BYS
- Consider renaming BYS

**Comment by afeld** [comment]
Wonder if this is worth revisiting, now that search from the Handbook also includes those other sites, the Development Guide has been renamed the Engineering Guide, etc.
