### ISSUE TITLE
 ATO Boundary Guidance and Documentation

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#432]
## User Story:
- As someone responsible for external services, I would like to know how to respond to questions about their ATO. 
- As someone who is responsible for external services, not sure if there's official guidance on this from GSA or NIST, but it would be useful to not have to re-figure this out every time. 
## Problem Statement: 
- The external systems have their own ATO, but within them, the system being assessed has users that are managed, data/logs being collected, etc. 
- In these cases, the "in/out of scope" boundary becomes a bit fuzzy.
- TTS will only be using more external services and inheritance over time, so this problem will grow.
## Background information: 
Note this applies to the documentation 
## Actions to take:  
- [ ] have canonical TTS documentation about how we use each service.
- [ ] guidance for assessors about what they should and shouldn't have to care about in each assessment.
## Acceptance criteria: 
- [ ] All ATOs are in a centralized repository
## Supporting Documentation:
[OpenControl](https://github.com/opencontrol/schemas)

**Comment by its-a-lisa** [comment]
@afeld I feel like the title of this card doesn't really represent what the card is asking, agree?

**Comment by afeld** [comment]
It's basically "figure out how our use of SaaS dependencies can be less confusing during the ATO process." I think this title is ok, but feel free to change if you have an idea for it.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
