### ISSUE TITLE
document New Relic use

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#512]
## Background Information

There are a few things for users to know about our New Relic configuration:

## Implementation Steps

Cover the following:

- [ ] [The configuration in Terraform](https://github.com/18F/newrelic-terraform)
- [ ] That is uses single sign-on through SecureAuth
   - [ ] That you need to be on the GSA network to do so
- [ ] That we have sub-accounts per program
   - [ ] How to get a new one

## Acceptance Criteria

- [ ] There's documentation explaining the TTS setup of New Relic
