### ISSUE TITLE
redirect homepage

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#539]
## Background Information

For the site to be considered fully decommissioned, we need all pages to redirect, especially the homepage.

## Implementation Steps

- [ ] Set up redirect
- [x] Leave a comment for Rachel Flagg in the [GSA site inventory](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit?ts=6025575d#gid=2013137748) that the `Production Status` should be changed to `Redirect`

## Acceptance Criteria

- [ ] https://before-you-ship.18f.gov/ redirects
